# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 51d805ea3286501a228106a01660ce836e6f262616a0a5533b076ee548250111c3023569830c106d77bb0661cb923b5712a532671bad01d4653f8514cbac7541

test:
  secret_key_base: ec172852a03b866e678ed2eea03aaca4cfdab73ca85d8aad09de8c8e14d5f4eaf345a518d6e5b12c9d3b4e315b8d256a4854c7415a341173e4c14790193c17ca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
